# Generated by Django 5.0.7 on 2024-07-17 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='images',
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_images', to='myapp.page')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='images',
            field=models.ManyToManyField(related_name='pages', to='myapp.image'),
        ),
    ]
